### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by Haroon-Sharif** [sindresorhus/alfred-dark-mode#1]
I don't understand how to use the code to actually install this workflow onto Alfred. Please, can you explain this in a simpler manner for a layman (like myself) to understand. Thanks for your workflow and help.

**Comment by sindresorhus** [comment]
You get [Node.js](https://nodejs.org/en/), then you run the following command in your terminal:

```
npm install --global alfred-dark-mode
```
