### ISSUE TITLE
Install fails if Alfred Preferences Stored in Dropbox / Non standard location

### ISSUE THREAD

**Issue by lewis-smith** [sindresorhus/alfred-dark-mode#4]
sudo npm install --global alfred-dark-mode
	Password:

	> alfred-dark-mode@1.0.0 postinstall /usr/local/lib/node_modules/alfred-dark-mode
	> alfred-link

	Error: Alfred preferences not found at location /Users/lewis/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
	    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-dark-mode/node_modules/resolve-alfred-prefs/index.js:15:10)
	    at <anonymous>
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! alfred-dark-mode@1.0.0 postinstall: `alfred-link`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the alfred-dark-mode@1.0.0 postinstall script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/lewis/.npm/_logs/2018-09-27T15_19_13_028Z-debug.log

**Comment by sindresorhus** [comment]
Can you move this issue to https://github.com/SamVerschueren/alfred-link ?
