### ISSUE TITLE
Install not working...

### ISSUE THREAD

**Issue by vpicouet** [sindresorhus/alfred-dark-mode#6]
![Capture d’écran, le 2021-05-02 à 21 52 43](https://user-images.githubusercontent.com/37241971/116825722-baa5cb00-ab90-11eb-9460-0d96b0a85566.jpg)

Do you know how to solve this?

**Comment by sindresorhus** [comment]
Open an issue on `resolve-alfred-prefs`. That's where the error is coming from.
